# myList = ["Shahan","Waheed",21,3.02,True,'S'];
# print(myList)
# print(myList[1])
# print(myList[5])
# # methods of list 
# Name = ["Shahan","Sameer","Fahad","Talat","Sonu","Huzaifa"]
# Name.append("Awais")
# print(Name)
# Name.insert(2,"Azlan")
# print(Name)
# Name.reverse()
# print(Name)
# Name.sort()
# print(Name)
# value = Name.count("Shahan")
# print(value)
# Name.extend(["Ashtar","Amaar","Farhad"])
# print(Name)
# p = Name.pop(2)
# print(p)
# print(Name)
# # Name.remove("Shahan")

# # print(Name)

# Marks = [89,95,92.67,59,90,85,82]
# print(Marks)
# # Marks.sort()
# # print(Marks)
# # Marks.reverse()
# # print(Marks)
# # Marks.append(49)
# # print(Marks)
# Marks.pop(2)
# print(Marks)
# # Marks.remove(89)
# # print(Marks)
# Marks.insert(4,73)
# print(Marks)
# Marks.extend([49,67,93])
# print(Marks)
# c = Marks.count(73)
# print(c)
# Marks.clear()
# print(Marks)